#!/usr/bin/env bash
# configures another server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "30i /listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "27i add_header X-Served-By \$HOSTNAME;\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "40i /listen 80 default_server;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
