#!/usr/bin/env bash
# configures another server
#sudo apt -y update
#sudo apt -y upgrade
#sudo apt -y install nginx
#sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "27i add_header X-Served-By \$HOSTNAME/" > /etc/nginx/sites-available/default
sudo service nginx restart
