#!/usr/bin/env bash
# configures another server
SRC="/etc/nginx/sites-available/default"
REDIR="\\\tlocation /redirectme {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
ERRDIR="\\\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
HEADER="\\\n\tadd_header X-Served-By \$HOSTNAME;\n"
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "27i $Header" $SRC
sudo sed -i "29i $REDIR" $SRC
sudo sed -i "47i $ERRDIR" $SRC
sudo service nginx restart
